/**
 * Blog LLM Chain — OpenRouter Only
 *
 * Single-provider chain using OpenRouter's free tier.
 * No fallback to Groq or Google AI — user requested OpenRouter exclusively.
 *
 * Model selection per purpose:
 *   - draft:    google/gemini-2.5-flash (fast, good JSON output)
 *   - expand:   google/gemini-2.5-flash (small task, fast)
 *   - alt-text: google/gemini-2.5-flash (tiny task)
 *
 * Free tier: ~20 RPM, ~200 RPD via OpenRouter.
 */

export type Message = { role: "system" | "user" | "assistant"; content: string };

export type BlogChatInput = {
  purpose: "draft" | "expand" | "alt-text";
  messages: Message[];
  temperature?: number;
  max_tokens?: number;
  response_format?: unknown;
};

export type BlogChatResponse = {
  content: string;
  provider: "openrouter" | "local-test";
  model: string;
  latency_ms: number;
};

const MODEL_MAP: Record<BlogChatInput["purpose"], string> = {
  draft: "google/gemini-2.5-flash",
  expand: "google/gemini-2.5-flash",
  "alt-text": "google/gemini-2.5-flash",
};

const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";

const OPENROUTER_HEADERS: Record<string, string> = {
  "X-Title": "VisaClarity Blog",
};

// Timeout per purpose (ms)
const TIMEOUT_MAP: Record<BlogChatInput["purpose"], number> = {
  draft: 60000, // 60s — full article generation can be slow
  expand: 15000, // 15s — small JSON response
  "alt-text": 10000, // 10s — tiny response
};

/**
 * Sleep helper for retry backoff.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Single attempt to call OpenRouter.
 */
async function callOpenRouter(
  apiKey: string,
  model: string,
  input: BlogChatInput,
  timeoutMs: number,
): Promise<{ content: string; status: number }> {
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), timeoutMs);

  try {
    const res = await fetch(OPENROUTER_URL, {
      method: "POST",
      signal: ctl.signal,
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
        "HTTP-Referer": process.env.VITE_SITE_URL || "https://visaclarity.lovable.app",
        ...OPENROUTER_HEADERS,
      },
      body: JSON.stringify({
        model,
        messages: input.messages,
        temperature: input.temperature ?? 0.4,
        max_tokens: input.max_tokens ?? 4000,
        ...(input.response_format ? { response_format: input.response_format } : {}),
      }),
    });

    clearTimeout(timer);

    if (!res.ok) {
      const text = await res.text().catch(() => "");
      const err: any = new Error(`OpenRouter ${res.status}: ${text.slice(0, 200)}`);
      err.status = res.status;
      throw err;
    }

    const data = await res.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("OpenRouter returned empty response");
    }

    return { content, status: res.status };
  } catch (err: any) {
    clearTimeout(timer);
    if (err.name === "AbortError") {
      throw new Error(`OpenRouter timed out after ${timeoutMs}ms`);
    }
    throw err;
  }
}

/**
 * Main entry point — call OpenRouter with retry on 429.
 *
 * Retry strategy: 1 retry with 3s backoff on 429 (rate limit).
 * All other errors fail immediately.
 */
export async function blogChatCompletion(input: BlogChatInput): Promise<BlogChatResponse> {
  // Local dry-run mode — return canned response for smoke tests
  if (process.env.BLOG_AGENT_LOCAL_TEST === "1") {
    const canned = JSON.stringify({
      refusal: null,
      title: "Test Article for Local Run",
      subtitle: "Auto-generated smoke test article",
      description: "This is a generated description for local testing purposes only.",
      category: "Guide",
      reading_minutes: 1,
      tldr: ["This is a test.", "No external calls were made.", "QA may be minimal."],
      body_mdx:
        "## TL;DR\n\nThis article is a smoke-test generated locally.\n\n## Introduction\n\nThis is a test article generated by the local dry-run mode. It exists to verify the pipeline works end-to-end without making real API calls.\n\n## Key Points\n\nThe blog generation system uses OpenRouter as its sole LLM provider. It generates articles from queued keywords, runs quality checks, and saves posts for human review.\n\n## What to Do Next\n\n1. Verify the pipeline completes without errors\n2. Check that the post appears in the admin UI\n3. Review the quality score in the QA panel",
      sources_used: [],
      needs_source_count: 0,
      hero_image_prompt:
        "A simple editorial photo of a laptop and notebook on a desk, natural light",
      confidence: "low",
      voice_notes: "Matched a neutral, concise voice.",
    });

    if (input.purpose === "expand") {
      const expandCanned = JSON.stringify({
        topic: "How to Apply for a Student Visa in the USA: Complete Guide",
        primary_keyword: "student visa USA",
        secondary_keywords: ["F-1 visa requirements", "US student visa process", "I-20 form"],
        audience: "International students applying to US universities",
        angle: "Step-by-step with common pitfalls",
        search_queries: [
          "F-1 student visa USA requirements",
          "US student visa application process",
        ],
      });
      return {
        content: expandCanned,
        provider: "local-test",
        model: "local",
        latency_ms: 5,
      };
    }

    if (input.purpose === "alt-text") {
      return {
        content: "A laptop and notebook on a desk bathed in natural light",
        provider: "local-test",
        model: "local",
        latency_ms: 2,
      };
    }

    return {
      content: canned,
      provider: "local-test",
      model: "local",
      latency_ms: 10,
    };
  }

  // Production path — OpenRouter only
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    throw new Error("OPENROUTER_API_KEY is not set. This is the only LLM provider configured.");
  }

  const model = MODEL_MAP[input.purpose];
  const timeoutMs = TIMEOUT_MAP[input.purpose];
  const startTime = Date.now();
  const MAX_RETRIES = 1;

  let lastError: Error | null = null;

  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const result = await callOpenRouter(apiKey, model, input, timeoutMs);

      return {
        content: result.content,
        provider: "openrouter",
        model,
        latency_ms: Date.now() - startTime,
      };
    } catch (err: any) {
      lastError = err;

      // Only retry on 429 (rate limit)
      if (err.status === 429 && attempt < MAX_RETRIES) {
        await sleep(3000); // 3s backoff
        continue;
      }

      // All other errors — fail immediately
      break;
    }
  }

  throw new Error(
    `OpenRouter failed for purpose="${input.purpose}": ${lastError?.message ?? "Unknown error"}`,
  );
}

export default { blogChatCompletion };
