/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as BlogAuthorSlugRouteImport } from './routes/blog.author.$slug'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as ApiPublicHooksCraftPersonalizedRoadmapRouteImport } from './routes/api/public/hooks/craft-personalized-roadmap'
import { Route as ApiPublicBlogGenerateRouteImport } from './routes/api/public/blog.generate'
import { Route as ApiPublicBlogBatchRouteImport } from './routes/api/public/blog.batch'
import { Route as ApiPublicHooksBlogCronRouteImport } from './routes/api/public/hooks/blog.cron'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BlogAuthorSlugRoute = BlogAuthorSlugRouteImport.update({
  id: '/blog/author/$slug',
  path: '/blog/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksCraftPersonalizedRoadmapRoute =
  ApiPublicHooksCraftPersonalizedRoadmapRouteImport.update({
    id: '/api/public/hooks/craft-personalized-roadmap',
    path: '/api/public/hooks/craft-personalized-roadmap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlogGenerateRoute = ApiPublicBlogGenerateRouteImport.update({
  id: '/api/public/blog/generate',
  path: '/api/public/blog/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlogBatchRoute = ApiPublicBlogBatchRouteImport.update({
  id: '/api/public/blog/batch',
  path: '/api/public/blog/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBlogCronRoute = ApiPublicHooksBlogCronRouteImport.update({
  id: '/api/public/hooks/blog/cron',
  path: '/api/public/hooks/blog/cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/api/public/blog/batch': typeof ApiPublicBlogBatchRoute
  '/api/public/blog/generate': typeof ApiPublicBlogGenerateRoute
  '/api/public/hooks/craft-personalized-roadmap': typeof ApiPublicHooksCraftPersonalizedRoadmapRoute
  '/api/public/hooks/blog/cron': typeof ApiPublicHooksBlogCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/api/public/blog/batch': typeof ApiPublicBlogBatchRoute
  '/api/public/blog/generate': typeof ApiPublicBlogGenerateRoute
  '/api/public/hooks/craft-personalized-roadmap': typeof ApiPublicHooksCraftPersonalizedRoadmapRoute
  '/api/public/hooks/blog/cron': typeof ApiPublicHooksBlogCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/blog/author/$slug': typeof BlogAuthorSlugRoute
  '/api/public/blog/batch': typeof ApiPublicBlogBatchRoute
  '/api/public/blog/generate': typeof ApiPublicBlogGenerateRoute
  '/api/public/hooks/craft-personalized-roadmap': typeof ApiPublicHooksCraftPersonalizedRoadmapRoute
  '/api/public/hooks/blog/cron': typeof ApiPublicHooksBlogCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/pricing'
    | '/roadmap'
    | '/sitemap.xml'
    | '/dashboard'
    | '/blog/$slug'
    | '/r/$slug'
    | '/blog/'
    | '/admin/blog'
    | '/blog/author/$slug'
    | '/api/public/blog/batch'
    | '/api/public/blog/generate'
    | '/api/public/hooks/craft-personalized-roadmap'
    | '/api/public/hooks/blog/cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/pricing'
    | '/roadmap'
    | '/sitemap.xml'
    | '/dashboard'
    | '/blog/$slug'
    | '/r/$slug'
    | '/blog'
    | '/admin/blog'
    | '/blog/author/$slug'
    | '/api/public/blog/batch'
    | '/api/public/blog/generate'
    | '/api/public/hooks/craft-personalized-roadmap'
    | '/api/public/hooks/blog/cron'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/pricing'
    | '/roadmap'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/r/$slug'
    | '/blog/'
    | '/_authenticated/admin/blog'
    | '/blog/author/$slug'
    | '/api/public/blog/batch'
    | '/api/public/blog/generate'
    | '/api/public/hooks/craft-personalized-roadmap'
    | '/api/public/hooks/blog/cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RSlugRoute: typeof RSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogAuthorSlugRoute: typeof BlogAuthorSlugRoute
  ApiPublicBlogBatchRoute: typeof ApiPublicBlogBatchRoute
  ApiPublicBlogGenerateRoute: typeof ApiPublicBlogGenerateRoute
  ApiPublicHooksCraftPersonalizedRoadmapRoute: typeof ApiPublicHooksCraftPersonalizedRoadmapRoute
  ApiPublicHooksBlogCronRoute: typeof ApiPublicHooksBlogCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/blog/author/$slug': {
      id: '/blog/author/$slug'
      path: '/blog/author/$slug'
      fullPath: '/blog/author/$slug'
      preLoaderRoute: typeof BlogAuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/craft-personalized-roadmap': {
      id: '/api/public/hooks/craft-personalized-roadmap'
      path: '/api/public/hooks/craft-personalized-roadmap'
      fullPath: '/api/public/hooks/craft-personalized-roadmap'
      preLoaderRoute: typeof ApiPublicHooksCraftPersonalizedRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog/generate': {
      id: '/api/public/blog/generate'
      path: '/api/public/blog/generate'
      fullPath: '/api/public/blog/generate'
      preLoaderRoute: typeof ApiPublicBlogGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog/batch': {
      id: '/api/public/blog/batch'
      path: '/api/public/blog/batch'
      fullPath: '/api/public/blog/batch'
      preLoaderRoute: typeof ApiPublicBlogBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/blog/cron': {
      id: '/api/public/hooks/blog/cron'
      path: '/api/public/hooks/blog/cron'
      fullPath: '/api/public/hooks/blog/cron'
      preLoaderRoute: typeof ApiPublicHooksBlogCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  RSlugRoute: RSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogAuthorSlugRoute: BlogAuthorSlugRoute,
  ApiPublicBlogBatchRoute: ApiPublicBlogBatchRoute,
  ApiPublicBlogGenerateRoute: ApiPublicBlogGenerateRoute,
  ApiPublicHooksCraftPersonalizedRoadmapRoute:
    ApiPublicHooksCraftPersonalizedRoadmapRoute,
  ApiPublicHooksBlogCronRoute: ApiPublicHooksBlogCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
